# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
jobs:
  build:
    docker:
      - image: circleci/rust:1.43.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - deps-{{ checksum "cargo.lock" }}-{{ checksum "core/cargo.lock" }}-{{ checksum "wasm/cargo.lock" }}
      - run: make ci
      - save_cache:
          keys:
            - deps-{{ checksum "cargo.lock" }}-{{ checksum "core/cargo.lock" }}-{{ checksum "wasm/cargo.lock" }}
