# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
jobs:
  build:
    docker:
      - image: circleci/rust:1.50.0
    steps:
      - checkout
      - run: make ci
  test:
    docker:
      - image: circleci/rust:1.50.0
    steps:
      - checkout
      - run: make test
  format:
    docker:
      - image: circleci/rust:1.50.0
    steps:
      - checkout
      - run: cargo fmt

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
      - format
