use AdressingMode::*;
use CycleCount::*;

pub struct Instruction<'a> {
    pub opcode: u8,
    pub repr: &'a str,
    pub num_bytes: u32,
    pub cycles: CycleCount,
    pub addressing_mode: AdressingMode,
}

pub enum AdressingMode {
    Implied,
    Imm8,
    Imm16,
    Addr16,
    ZeroPageOffset,
    SignedAddrOffset,
}

pub enum CycleCount {
    Fixed(u32),
    // Jump(cycles_if_jump_occurs, cycles_if_no_jump_occurs)
    Jump(u32, u32),
}

impl CycleCount {
    pub fn get_extra_cycles(&self) -> u32 {
        match self {
            Fixed(_) => 0,
            Jump(cycles_if_jump_occurs, cycles_if_no_jump_occurs) => {
                cycles_if_jump_occurs - cycles_if_no_jump_occurs
            }
        }
    }
}

pub const INSTRUCTIONS: [Instruction; 256] = [
    Instruction { opcode: 0x00, repr: "NOP", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0x01, repr: "LD BC,d16", num_bytes: 3, cycles: Fixed(3), addressing_mode: Imm16 },
    Instruction { opcode: 0x02, repr: "LD (BC),A", num_bytes: 1, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x03, repr: "INC BC", num_bytes: 1, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x04, repr: "INC B", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0x05, repr: "DEC B", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0x06, repr: "LD B,d8", num_bytes: 2, cycles: Fixed(2), addressing_mode: Imm8 },
    Instruction { opcode: 0x07, repr: "RLCA", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0x08, repr: "LD (a16),SP", num_bytes: 3, cycles: Fixed(5), addressing_mode: Addr16 },
    Instruction { opcode: 0x09, repr: "ADD HL,BC", num_bytes: 1, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x0A, repr: "LD A,(BC)", num_bytes: 1, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x0B, repr: "DEC BC", num_bytes: 1, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x0C, repr: "INC C", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0x0D, repr: "DEC C", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0x0E, repr: "LD C,d8", num_bytes: 2, cycles: Fixed(2), addressing_mode: Imm8 },
    Instruction { opcode: 0x0F, repr: "RRCA", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0x10, repr: "STOP 0", num_bytes: 2, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0x11, repr: "LD DE,d16", num_bytes: 3, cycles: Fixed(3), addressing_mode: Imm16 },
    Instruction { opcode: 0x12, repr: "LD (DE),A", num_bytes: 1, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x13, repr: "INC DE", num_bytes: 1, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x14, repr: "INC D", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0x15, repr: "DEC D", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0x16, repr: "LD D,d8", num_bytes: 2, cycles: Fixed(2), addressing_mode: Imm8 },
    Instruction { opcode: 0x17, repr: "RLA", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0x18, repr: "JR r8", num_bytes: 2, cycles: Fixed(3), addressing_mode: SignedAddrOffset },
    Instruction { opcode: 0x19, repr: "ADD HL,DE", num_bytes: 1, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x1A, repr: "LD A,(DE)", num_bytes: 1, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x1B, repr: "DEC DE", num_bytes: 1, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x1C, repr: "INC E", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0x1D, repr: "DEC E", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0x1E, repr: "LD E,d8", num_bytes: 2, cycles: Fixed(2), addressing_mode: Imm8 },
    Instruction { opcode: 0x1F, repr: "RRA", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0x20, repr: "JR NZ,r8", num_bytes: 2, cycles: Jump(3, 2), addressing_mode: SignedAddrOffset },
    Instruction { opcode: 0x21, repr: "LD HL,d16", num_bytes: 3, cycles: Fixed(3), addressing_mode: Imm16 },
    Instruction { opcode: 0x22, repr: "LD (HL+),A", num_bytes: 1, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x23, repr: "INC HL", num_bytes: 1, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x24, repr: "INC H", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0x25, repr: "DEC H", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0x26, repr: "LD H,d8", num_bytes: 2, cycles: Fixed(2), addressing_mode: Imm8 },
    Instruction { opcode: 0x27, repr: "DAA", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0x28, repr: "JR Z,r8", num_bytes: 2, cycles: Jump(3, 2), addressing_mode: SignedAddrOffset },
    Instruction { opcode: 0x29, repr: "ADD HL,HL", num_bytes: 1, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x2A, repr: "LD A,(HL+)", num_bytes: 1, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x2B, repr: "DEC HL", num_bytes: 1, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x2C, repr: "INC L", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0x2D, repr: "DEC L", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0x2E, repr: "LD L,d8", num_bytes: 2, cycles: Fixed(2), addressing_mode: Imm8 },
    Instruction { opcode: 0x2F, repr: "CPL", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0x30, repr: "JR NC,r8", num_bytes: 2, cycles: Jump(3, 2), addressing_mode: SignedAddrOffset },
    Instruction { opcode: 0x31, repr: "LD SP,d16", num_bytes: 3, cycles: Fixed(3), addressing_mode: Imm16 },
    Instruction { opcode: 0x32, repr: "LD (HL-),A", num_bytes: 1, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x33, repr: "INC SP", num_bytes: 1, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x34, repr: "INC (HL)", num_bytes: 1, cycles: Fixed(3), addressing_mode: Implied },
    Instruction { opcode: 0x35, repr: "DEC (HL)", num_bytes: 1, cycles: Fixed(3), addressing_mode: Implied },
    Instruction { opcode: 0x36, repr: "LD (HL),d8", num_bytes: 2, cycles: Fixed(3), addressing_mode: Imm8 },
    Instruction { opcode: 0x37, repr: "SCF", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0x38, repr: "JR C,r8", num_bytes: 2, cycles: Jump(3, 2), addressing_mode: SignedAddrOffset },
    Instruction { opcode: 0x39, repr: "ADD HL,SP", num_bytes: 1, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x3A, repr: "LD A,(HL-)", num_bytes: 1, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x3B, repr: "DEC SP", num_bytes: 1, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x3C, repr: "INC A", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0x3D, repr: "DEC A", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0x3E, repr: "LD A,d8", num_bytes: 2, cycles: Fixed(2), addressing_mode: Imm8 },
    Instruction { opcode: 0x3F, repr: "CCF", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0x40, repr: "LD B,B", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0x41, repr: "LD B,C", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0x42, repr: "LD B,D", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0x43, repr: "LD B,E", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0x44, repr: "LD B,H", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0x45, repr: "LD B,L", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0x46, repr: "LD B,(HL)", num_bytes: 1, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x47, repr: "LD B,A", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0x48, repr: "LD C,B", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0x49, repr: "LD C,C", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0x4A, repr: "LD C,D", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0x4B, repr: "LD C,E", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0x4C, repr: "LD C,H", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0x4D, repr: "LD C,L", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0x4E, repr: "LD C,(HL)", num_bytes: 1, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x4F, repr: "LD C,A", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0x50, repr: "LD D,B", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0x51, repr: "LD D,C", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0x52, repr: "LD D,D", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0x53, repr: "LD D,E", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0x54, repr: "LD D,H", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0x55, repr: "LD D,L", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0x56, repr: "LD D,(HL)", num_bytes: 1, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x57, repr: "LD D,A", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0x58, repr: "LD E,B", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0x59, repr: "LD E,C", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0x5A, repr: "LD E,D", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0x5B, repr: "LD E,E", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0x5C, repr: "LD E,H", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0x5D, repr: "LD E,L", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0x5E, repr: "LD E,(HL)", num_bytes: 1, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x5F, repr: "LD E,A", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0x60, repr: "LD H,B", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0x61, repr: "LD H,C", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0x62, repr: "LD H,D", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0x63, repr: "LD H,E", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0x64, repr: "LD H,H", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0x65, repr: "LD H,L", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0x66, repr: "LD H,(HL)", num_bytes: 1, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x67, repr: "LD H,A", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0x68, repr: "LD L,B", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0x69, repr: "LD L,C", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0x6A, repr: "LD L,D", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0x6B, repr: "LD L,E", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0x6C, repr: "LD L,H", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0x6D, repr: "LD L,L", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0x6E, repr: "LD L,(HL)", num_bytes: 1, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x6F, repr: "LD L,A", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0x70, repr: "LD (HL),B", num_bytes: 1, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x71, repr: "LD (HL),C", num_bytes: 1, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x72, repr: "LD (HL),D", num_bytes: 1, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x73, repr: "LD (HL),E", num_bytes: 1, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x74, repr: "LD (HL),H", num_bytes: 1, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x75, repr: "LD (HL),L", num_bytes: 1, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x76, repr: "HALT", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0x77, repr: "LD (HL),A", num_bytes: 1, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x78, repr: "LD A,B", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0x79, repr: "LD A,C", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0x7A, repr: "LD A,D", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0x7B, repr: "LD A,E", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0x7C, repr: "LD A,H", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0x7D, repr: "LD A,L", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0x7E, repr: "LD A,(HL)", num_bytes: 1, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x7F, repr: "LD A,A", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0x80, repr: "ADD A,B", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0x81, repr: "ADD A,C", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0x82, repr: "ADD A,D", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0x83, repr: "ADD A,E", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0x84, repr: "ADD A,H", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0x85, repr: "ADD A,L", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0x86, repr: "ADD A,(HL)", num_bytes: 1, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x87, repr: "ADD A,A", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0x88, repr: "ADC A,B", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0x89, repr: "ADC A,C", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0x8A, repr: "ADC A,D", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0x8B, repr: "ADC A,E", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0x8C, repr: "ADC A,H", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0x8D, repr: "ADC A,L", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0x8E, repr: "ADC A,(HL)", num_bytes: 1, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x8F, repr: "ADC A,A", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0x90, repr: "SUB B", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0x91, repr: "SUB C", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0x92, repr: "SUB D", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0x93, repr: "SUB E", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0x94, repr: "SUB H", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0x95, repr: "SUB L", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0x96, repr: "SUB (HL)", num_bytes: 1, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x97, repr: "SUB A", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0x98, repr: "SBC A,B", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0x99, repr: "SBC A,C", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0x9A, repr: "SBC A,D", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0x9B, repr: "SBC A,E", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0x9C, repr: "SBC A,H", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0x9D, repr: "SBC A,L", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0x9E, repr: "SBC A,(HL)", num_bytes: 1, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x9F, repr: "SBC A,A", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0xA0, repr: "AND B", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0xA1, repr: "AND C", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0xA2, repr: "AND D", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0xA3, repr: "AND E", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0xA4, repr: "AND H", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0xA5, repr: "AND L", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0xA6, repr: "AND (HL)", num_bytes: 1, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0xA7, repr: "AND A", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0xA8, repr: "XOR B", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0xA9, repr: "XOR C", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0xAA, repr: "XOR D", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0xAB, repr: "XOR E", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0xAC, repr: "XOR H", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0xAD, repr: "XOR L", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0xAE, repr: "XOR (HL)", num_bytes: 1, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0xAF, repr: "XOR A", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0xB0, repr: "OR B", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0xB1, repr: "OR C", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0xB2, repr: "OR D", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0xB3, repr: "OR E", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0xB4, repr: "OR H", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0xB5, repr: "OR L", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0xB6, repr: "OR (HL)", num_bytes: 1, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0xB7, repr: "OR A", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0xB8, repr: "CP B", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0xB9, repr: "CP C", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0xBA, repr: "CP D", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0xBB, repr: "CP E", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0xBC, repr: "CP H", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0xBD, repr: "CP L", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0xBE, repr: "CP (HL)", num_bytes: 1, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0xBF, repr: "CP A", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0xC0, repr: "RET NZ", num_bytes: 1, cycles: Jump(5, 2), addressing_mode: Implied },
    Instruction { opcode: 0xC1, repr: "POP BC", num_bytes: 1, cycles: Fixed(3), addressing_mode: Implied },
    Instruction { opcode: 0xC2, repr: "JP NZ,a16", num_bytes: 3, cycles: Jump(4, 3), addressing_mode: Addr16 },
    Instruction { opcode: 0xC3, repr: "JP a16", num_bytes: 3, cycles: Fixed(4), addressing_mode: Addr16 },
    Instruction { opcode: 0xC4, repr: "CALL NZ,a16", num_bytes: 3, cycles: Jump(6, 3), addressing_mode: Addr16 },
    Instruction { opcode: 0xC5, repr: "PUSH BC", num_bytes: 1, cycles: Fixed(4), addressing_mode: Implied },
    Instruction { opcode: 0xC6, repr: "ADD A,d8", num_bytes: 2, cycles: Fixed(2), addressing_mode: Imm8 },
    Instruction { opcode: 0xC7, repr: "RST 00H", num_bytes: 1, cycles: Fixed(4), addressing_mode: Implied },
    Instruction { opcode: 0xC8, repr: "RET Z", num_bytes: 1, cycles: Jump(5, 2), addressing_mode: Implied },
    Instruction { opcode: 0xC9, repr: "RET", num_bytes: 1, cycles: Fixed(4), addressing_mode: Implied },
    Instruction { opcode: 0xCA, repr: "JP Z,a16", num_bytes: 3, cycles: Jump(4, 3), addressing_mode: Addr16 },
    Instruction { opcode: 0xCB, repr: "PREFIX CB", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0xCC, repr: "CALL Z,a16", num_bytes: 3, cycles: Jump(6, 3), addressing_mode: Addr16 },
    Instruction { opcode: 0xCD, repr: "CALL a16", num_bytes: 3, cycles: Fixed(6), addressing_mode: Addr16 },
    Instruction { opcode: 0xCE, repr: "ADC A,d8", num_bytes: 2, cycles: Fixed(2), addressing_mode: Imm8 },
    Instruction { opcode: 0xCF, repr: "RST 08H", num_bytes: 1, cycles: Fixed(4), addressing_mode: Implied },
    Instruction { opcode: 0xD0, repr: "RET NC", num_bytes: 1, cycles: Jump(5, 2), addressing_mode: Implied },
    Instruction { opcode: 0xD1, repr: "POP DE", num_bytes: 1, cycles: Fixed(3), addressing_mode: Implied },
    Instruction { opcode: 0xD2, repr: "JP NC,a16", num_bytes: 3, cycles: Jump(4, 3), addressing_mode: Addr16 },
    Instruction { opcode: 0xD3, repr: "UNIMPLEMENTED", num_bytes: 0, cycles: Fixed(0), addressing_mode: Addr16 },
    Instruction { opcode: 0xD4, repr: "CALL NC,a16", num_bytes: 3, cycles: Jump(6, 3), addressing_mode: Addr16 },
    Instruction { opcode: 0xD5, repr: "PUSH DE", num_bytes: 1, cycles: Fixed(4), addressing_mode: Implied },
    Instruction { opcode: 0xD6, repr: "SUB d8", num_bytes: 2, cycles: Fixed(2), addressing_mode: Imm8 },
    Instruction { opcode: 0xD7, repr: "RST 10H", num_bytes: 1, cycles: Fixed(4), addressing_mode: Implied },
    Instruction { opcode: 0xD8, repr: "RET C", num_bytes: 1, cycles: Jump(5, 2), addressing_mode: Implied },
    Instruction { opcode: 0xD9, repr: "RETI", num_bytes: 1, cycles: Fixed(4), addressing_mode: Implied },
    Instruction { opcode: 0xDA, repr: "JP C,a16", num_bytes: 3, cycles: Jump(4, 3), addressing_mode: Addr16 },
    Instruction { opcode: 0xDB, repr: "UNIMPLEMENTED", num_bytes: 0, cycles: Fixed(0), addressing_mode: Addr16 },
    Instruction { opcode: 0xDC, repr: "CALL C,a16", num_bytes: 3, cycles: Jump(6, 3), addressing_mode: Addr16 },
    Instruction { opcode: 0xDD, repr: "UNIMPLEMENTED", num_bytes: 0, cycles: Fixed(0), addressing_mode: Addr16 },
    Instruction { opcode: 0xDE, repr: "SBC A,d8", num_bytes: 2, cycles: Fixed(2), addressing_mode: Imm8 },
    Instruction { opcode: 0xDF, repr: "RST 18H", num_bytes: 1, cycles: Fixed(4), addressing_mode: Implied },
    Instruction { opcode: 0xE0, repr: "LDH (a8),A", num_bytes: 2, cycles: Fixed(3), addressing_mode: ZeroPageOffset },
    Instruction { opcode: 0xE1, repr: "POP HL", num_bytes: 1, cycles: Fixed(3), addressing_mode: Implied },
    Instruction { opcode: 0xE2, repr: "LD (C),A", num_bytes: 1, cycles: Fixed(2), addressing_mode: ZeroPageOffset },
    Instruction { opcode: 0xE3, repr: "UNIMPLEMENTED", num_bytes: 0, cycles: Fixed(0), addressing_mode: ZeroPageOffset },
    Instruction { opcode: 0xE4, repr: "UNIMPLEMENTED", num_bytes: 0, cycles: Fixed(0), addressing_mode: ZeroPageOffset },
    Instruction { opcode: 0xE5, repr: "PUSH HL", num_bytes: 1, cycles: Fixed(4), addressing_mode: Implied },
    Instruction { opcode: 0xE6, repr: "AND d8", num_bytes: 2, cycles: Fixed(2), addressing_mode: Imm8 },
    Instruction { opcode: 0xE7, repr: "RST 20H", num_bytes: 1, cycles: Fixed(4), addressing_mode: Implied },
    Instruction { opcode: 0xE8, repr: "ADD SP,r8", num_bytes: 2, cycles: Fixed(4), addressing_mode: SignedAddrOffset },
    Instruction { opcode: 0xE9, repr: "JP (HL)", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0xEA, repr: "LD (a16),A", num_bytes: 3, cycles: Fixed(4), addressing_mode: Addr16 },
    Instruction { opcode: 0xEB, repr: "UNIMPLEMENTED", num_bytes: 0, cycles: Fixed(0), addressing_mode: Addr16 },
    Instruction { opcode: 0xEC, repr: "UNIMPLEMENTED", num_bytes: 0, cycles: Fixed(0), addressing_mode: Addr16 },
    Instruction { opcode: 0xED, repr: "UNIMPLEMENTED", num_bytes: 0, cycles: Fixed(0), addressing_mode: Addr16 },
    Instruction { opcode: 0xEE, repr: "XOR d8", num_bytes: 2, cycles: Fixed(2), addressing_mode: Imm8 },
    Instruction { opcode: 0xEF, repr: "RST 28H", num_bytes: 1, cycles: Fixed(4), addressing_mode: Implied },
    Instruction { opcode: 0xF0, repr: "LDH A,(a8)", num_bytes: 2, cycles: Fixed(3), addressing_mode: ZeroPageOffset },
    Instruction { opcode: 0xF1, repr: "POP AF", num_bytes: 1, cycles: Fixed(3), addressing_mode: Implied },
    Instruction { opcode: 0xF2, repr: "LD A,(C)", num_bytes: 1, cycles: Fixed(2), addressing_mode: ZeroPageOffset },
    Instruction { opcode: 0xF3, repr: "DI", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0xF4, repr: "UNIMPLEMENTED", num_bytes: 0, cycles: Fixed(0), addressing_mode: Implied },
    Instruction { opcode: 0xF5, repr: "PUSH AF", num_bytes: 1, cycles: Fixed(4), addressing_mode: Implied },
    Instruction { opcode: 0xF6, repr: "OR d8", num_bytes: 2, cycles: Fixed(2), addressing_mode: Imm8 },
    Instruction { opcode: 0xF7, repr: "RST 30H", num_bytes: 1, cycles: Fixed(4), addressing_mode: Implied },
    Instruction { opcode: 0xF8, repr: "LD HL,SP+r8", num_bytes: 2, cycles: Fixed(3), addressing_mode: SignedAddrOffset },
    Instruction { opcode: 0xF9, repr: "LD SP,HL", num_bytes: 1, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0xFA, repr: "LD A,(a16)", num_bytes: 3, cycles: Fixed(4), addressing_mode: Addr16 },
    Instruction { opcode: 0xFB, repr: "EI", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0xFC, repr: "UNIMPLEMENTED", num_bytes: 0, cycles: Fixed(0), addressing_mode: Implied },
    Instruction { opcode: 0xFD, repr: "UNIMPLEMENTED", num_bytes: 0, cycles: Fixed(0), addressing_mode: Implied },
    Instruction { opcode: 0xFE, repr: "CP d8", num_bytes: 2, cycles: Fixed(2), addressing_mode: Imm8 },
    Instruction { opcode: 0xFF, repr: "RST 38H", num_bytes: 1, cycles: Fixed(4), addressing_mode: Implied },
];

pub const PREFIXED_INSTRUCTIONS: [Instruction; 256] = [
    Instruction { opcode: 0x00, repr: "RLC B", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x01, repr: "RLC C", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x02, repr: "RLC D", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x03, repr: "RLC E", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x04, repr: "RLC H", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x05, repr: "RLC L", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x06, repr: "RLC (HL)", num_bytes: 2, cycles: Fixed(4), addressing_mode: Implied },
    Instruction { opcode: 0x07, repr: "RLC A", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x08, repr: "RRC B", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x09, repr: "RRC C", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x0A, repr: "RRC D", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x0B, repr: "RRC E", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x0C, repr: "RRC H", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x0D, repr: "RRC L", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x0E, repr: "RRC (HL)", num_bytes: 2, cycles: Fixed(4), addressing_mode: Implied },
    Instruction { opcode: 0x0F, repr: "RRC A", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x10, repr: "RL B", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x11, repr: "RL C", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x12, repr: "RL D", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x13, repr: "RL E", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x14, repr: "RL H", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x15, repr: "RL L", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x16, repr: "RL (HL)", num_bytes: 2, cycles: Fixed(4), addressing_mode: Implied },
    Instruction { opcode: 0x17, repr: "RL A", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x18, repr: "RR B", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x19, repr: "RR C", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x1A, repr: "RR D", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x1B, repr: "RR E", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x1C, repr: "RR H", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x1D, repr: "RR L", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x1E, repr: "RR (HL)", num_bytes: 2, cycles: Fixed(4), addressing_mode: Implied },
    Instruction { opcode: 0x1F, repr: "RR A", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x20, repr: "SLA B", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x21, repr: "SLA C", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x22, repr: "SLA D", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x23, repr: "SLA E", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x24, repr: "SLA H", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x25, repr: "SLA L", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x26, repr: "SLA (HL)", num_bytes: 2, cycles: Fixed(4), addressing_mode: Implied },
    Instruction { opcode: 0x27, repr: "SLA A", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x28, repr: "SRA B", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x29, repr: "SRA C", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x2A, repr: "SRA D", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x2B, repr: "SRA E", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x2C, repr: "SRA H", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x2D, repr: "SRA L", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x2E, repr: "SRA (HL)", num_bytes: 2, cycles: Fixed(4), addressing_mode: Implied },
    Instruction { opcode: 0x2F, repr: "SRA A", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x30, repr: "SWAP B", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x31, repr: "SWAP C", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x32, repr: "SWAP D", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x33, repr: "SWAP E", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x34, repr: "SWAP H", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x35, repr: "SWAP L", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x36, repr: "SWAP (HL)", num_bytes: 2, cycles: Fixed(4), addressing_mode: Implied },
    Instruction { opcode: 0x37, repr: "SWAP A", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x38, repr: "SRL B", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x39, repr: "SRL C", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x3A, repr: "SRL D", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x3B, repr: "SRL E", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x3C, repr: "SRL H", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x3D, repr: "SRL L", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x3E, repr: "SRL (HL)", num_bytes: 2, cycles: Fixed(4), addressing_mode: Implied },
    Instruction { opcode: 0x3F, repr: "SRL A", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x40, repr: "BIT 0,B", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x41, repr: "BIT 0,C", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x42, repr: "BIT 0,D", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x43, repr: "BIT 0,E", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x44, repr: "BIT 0,H", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x45, repr: "BIT 0,L", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x46, repr: "BIT 0,(HL)", num_bytes: 2, cycles: Fixed(4), addressing_mode: Implied },
    Instruction { opcode: 0x47, repr: "BIT 0,A", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x48, repr: "BIT 1,B", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x49, repr: "BIT 1,C", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x4A, repr: "BIT 1,D", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x4B, repr: "BIT 1,E", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x4C, repr: "BIT 1,H", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x4D, repr: "BIT 1,L", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x4E, repr: "BIT 1,(HL)", num_bytes: 2, cycles: Fixed(4), addressing_mode: Implied },
    Instruction { opcode: 0x4F, repr: "BIT 1,A", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x50, repr: "BIT 2,B", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x51, repr: "BIT 2,C", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x52, repr: "BIT 2,D", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x53, repr: "BIT 2,E", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x54, repr: "BIT 2,H", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x55, repr: "BIT 2,L", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x56, repr: "BIT 2,(HL)", num_bytes: 2, cycles: Fixed(4), addressing_mode: Implied },
    Instruction { opcode: 0x57, repr: "BIT 2,A", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x58, repr: "BIT 3,B", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x59, repr: "BIT 3,C", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x5A, repr: "BIT 3,D", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x5B, repr: "BIT 3,E", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x5C, repr: "BIT 3,H", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x5D, repr: "BIT 3,L", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x5E, repr: "BIT 3,(HL)", num_bytes: 2, cycles: Fixed(4), addressing_mode: Implied },
    Instruction { opcode: 0x5F, repr: "BIT 3,A", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x60, repr: "BIT 4,B", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x61, repr: "BIT 4,C", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x62, repr: "BIT 4,D", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x63, repr: "BIT 4,E", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x64, repr: "BIT 4,H", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x65, repr: "BIT 4,L", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x66, repr: "BIT 4,(HL)", num_bytes: 2, cycles: Fixed(4), addressing_mode: Implied },
    Instruction { opcode: 0x67, repr: "BIT 4,A", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x68, repr: "BIT 5,B", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x69, repr: "BIT 5,C", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x6A, repr: "BIT 5,D", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x6B, repr: "BIT 5,E", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x6C, repr: "BIT 5,H", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x6D, repr: "BIT 5,L", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x6E, repr: "BIT 5,(HL)", num_bytes: 2, cycles: Fixed(4), addressing_mode: Implied },
    Instruction { opcode: 0x6F, repr: "BIT 5,A", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x70, repr: "BIT 6,B", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x71, repr: "BIT 6,C", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x72, repr: "BIT 6,D", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x73, repr: "BIT 6,E", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x74, repr: "BIT 6,H", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x75, repr: "BIT 6,L", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x76, repr: "BIT 6,(HL)", num_bytes: 2, cycles: Fixed(4), addressing_mode: Implied },
    Instruction { opcode: 0x77, repr: "BIT 6,A", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x78, repr: "BIT 7,B", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x79, repr: "BIT 7,C", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x7A, repr: "BIT 7,D", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x7B, repr: "BIT 7,E", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x7C, repr: "BIT 7,H", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x7D, repr: "BIT 7,L", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x7E, repr: "BIT 7,(HL)", num_bytes: 2, cycles: Fixed(4), addressing_mode: Implied },
    Instruction { opcode: 0x7F, repr: "BIT 7,A", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x80, repr: "RES 0,B", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x81, repr: "RES 0,C", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x82, repr: "RES 0,D", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x83, repr: "RES 0,E", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x84, repr: "RES 0,H", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x85, repr: "RES 0,L", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x86, repr: "RES 0,(HL)", num_bytes: 2, cycles: Fixed(4), addressing_mode: Implied },
    Instruction { opcode: 0x87, repr: "RES 0,A", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x88, repr: "RES 1,B", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x89, repr: "RES 1,C", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x8A, repr: "RES 1,D", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x8B, repr: "RES 1,E", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x8C, repr: "RES 1,H", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x8D, repr: "RES 1,L", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x8E, repr: "RES 1,(HL)", num_bytes: 2, cycles: Fixed(4), addressing_mode: Implied },
    Instruction { opcode: 0x8F, repr: "RES 1,A", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x90, repr: "RES 2,B", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x91, repr: "RES 2,C", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x92, repr: "RES 2,D", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x93, repr: "RES 2,E", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x94, repr: "RES 2,H", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x95, repr: "RES 2,L", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x96, repr: "RES 2,(HL)", num_bytes: 2, cycles: Fixed(4), addressing_mode: Implied },
    Instruction { opcode: 0x97, repr: "RES 2,A", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x98, repr: "RES 3,B", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x99, repr: "RES 3,C", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x9A, repr: "RES 3,D", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x9B, repr: "RES 3,E", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x9C, repr: "RES 3,H", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x9D, repr: "RES 3,L", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x9E, repr: "RES 3,(HL)", num_bytes: 2, cycles: Fixed(4), addressing_mode: Implied },
    Instruction { opcode: 0x9F, repr: "RES 3,A", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0xA0, repr: "RES 4,B", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0xA1, repr: "RES 4,C", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0xA2, repr: "RES 4,D", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0xA3, repr: "RES 4,E", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0xA4, repr: "RES 4,H", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0xA5, repr: "RES 4,L", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0xA6, repr: "RES 4,(HL)", num_bytes: 2, cycles: Fixed(4), addressing_mode: Implied },
    Instruction { opcode: 0xA7, repr: "RES 4,A", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0xA8, repr: "RES 5,B", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0xA9, repr: "RES 5,C", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0xAA, repr: "RES 5,D", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0xAB, repr: "RES 5,E", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0xAC, repr: "RES 5,H", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0xAD, repr: "RES 5,L", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0xAE, repr: "RES 5,(HL)", num_bytes: 2, cycles: Fixed(4), addressing_mode: Implied },
    Instruction { opcode: 0xAF, repr: "RES 5,A", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0xB0, repr: "RES 6,B", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0xB1, repr: "RES 6,C", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0xB2, repr: "RES 6,D", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0xB3, repr: "RES 6,E", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0xB4, repr: "RES 6,H", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0xB5, repr: "RES 6,L", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0xB6, repr: "RES 6,(HL)", num_bytes: 2, cycles: Fixed(4), addressing_mode: Implied },
    Instruction { opcode: 0xB7, repr: "RES 6,A", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0xB8, repr: "RES 7,B", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0xB9, repr: "RES 7,C", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0xBA, repr: "RES 7,D", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0xBB, repr: "RES 7,E", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0xBC, repr: "RES 7,H", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0xBD, repr: "RES 7,L", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0xBE, repr: "RES 7,(HL)", num_bytes: 2, cycles: Fixed(4), addressing_mode: Implied },
    Instruction { opcode: 0xBF, repr: "RES 7,A", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0xC0, repr: "SET 0,B", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0xC1, repr: "SET 0,C", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0xC2, repr: "SET 0,D", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0xC3, repr: "SET 0,E", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0xC4, repr: "SET 0,H", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0xC5, repr: "SET 0,L", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0xC6, repr: "SET 0,(HL)", num_bytes: 2, cycles: Fixed(4), addressing_mode: Implied },
    Instruction { opcode: 0xC7, repr: "SET 0,A", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0xC8, repr: "SET 1,B", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0xC9, repr: "SET 1,C", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0xCA, repr: "SET 1,D", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0xCB, repr: "SET 1,E", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0xCC, repr: "SET 1,H", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0xCD, repr: "SET 1,L", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0xCE, repr: "SET 1,(HL)", num_bytes: 2, cycles: Fixed(4), addressing_mode: Implied },
    Instruction { opcode: 0xCF, repr: "SET 1,A", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0xD0, repr: "SET 2,B", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0xD1, repr: "SET 2,C", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0xD2, repr: "SET 2,D", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0xD3, repr: "SET 2,E", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0xD4, repr: "SET 2,H", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0xD5, repr: "SET 2,L", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0xD6, repr: "SET 2,(HL)", num_bytes: 2, cycles: Fixed(4), addressing_mode: Implied },
    Instruction { opcode: 0xD7, repr: "SET 2,A", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0xD8, repr: "SET 3,B", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0xD9, repr: "SET 3,C", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0xDA, repr: "SET 3,D", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0xDB, repr: "SET 3,E", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0xDC, repr: "SET 3,H", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0xDD, repr: "SET 3,L", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0xDE, repr: "SET 3,(HL)", num_bytes: 2, cycles: Fixed(4), addressing_mode: Implied },
    Instruction { opcode: 0xDF, repr: "SET 3,A", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0xE0, repr: "SET 4,B", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0xE1, repr: "SET 4,C", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0xE2, repr: "SET 4,D", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0xE3, repr: "SET 4,E", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0xE4, repr: "SET 4,H", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0xE5, repr: "SET 4,L", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0xE6, repr: "SET 4,(HL)", num_bytes: 2, cycles: Fixed(4), addressing_mode: Implied },
    Instruction { opcode: 0xE7, repr: "SET 4,A", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0xE8, repr: "SET 5,B", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0xE9, repr: "SET 5,C", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0xEA, repr: "SET 5,D", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0xEB, repr: "SET 5,E", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0xEC, repr: "SET 5,H", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0xED, repr: "SET 5,L", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0xEE, repr: "SET 5,(HL)", num_bytes: 2, cycles: Fixed(4), addressing_mode: Implied },
    Instruction { opcode: 0xEF, repr: "SET 5,A", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0xF0, repr: "SET 6,B", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0xF1, repr: "SET 6,C", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0xF2, repr: "SET 6,D", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0xF3, repr: "SET 6,E", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0xF4, repr: "SET 6,H", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0xF5, repr: "SET 6,L", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0xF6, repr: "SET 6,(HL)", num_bytes: 2, cycles: Fixed(4), addressing_mode: Implied },
    Instruction { opcode: 0xF7, repr: "SET 6,A", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0xF8, repr: "SET 7,B", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0xF9, repr: "SET 7,C", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0xFA, repr: "SET 7,D", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0xFB, repr: "SET 7,E", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0xFC, repr: "SET 7,H", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0xFD, repr: "SET 7,L", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0xFE, repr: "SET 7,(HL)", num_bytes: 2, cycles: Fixed(4), addressing_mode: Implied },
    Instruction { opcode: 0xFF, repr: "SET 7,A", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
];
