use AddressingMode::*;
use CycleCount::*;

#[derive(Debug)]
pub struct Instruction<'a> {
    pub opcode: u8,
    pub repr: &'a str,
    pub num_bytes: u32,
    pub cycles: CycleCount,
    pub addressing_mode: AddressingMode,
    pub prefixed: bool,
}

#[derive(Debug)]
pub enum AddressingMode {
    Implied,
    Imm8,
    Imm16,
    Addr16,
    ZeroPageOffset,
    SignedAddrOffset,
}

#[derive(Debug)]
pub enum CycleCount {
    Fixed(u32),
    // Jump(cycles_if_jump_occurs, cycles_if_no_jump_occurs)
    Jump(u32, u32),
}

impl CycleCount {
    pub fn get_extra_cycles(&self) -> u32 {
        match self {
            Fixed(_) => 0,
            Jump(cycles_if_jump_occurs, cycles_if_no_jump_occurs) => {
                cycles_if_jump_occurs - cycles_if_no_jump_occurs
            }
        }
    }
}

pub static INSTRUCTIONS: [Instruction; 256] = [
    Instruction { opcode: 0x00, prefixed: false, repr: "NOP", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0x01, prefixed: false, repr: "LD BC,d16", num_bytes: 3, cycles: Fixed(3), addressing_mode: Imm16 },
    Instruction { opcode: 0x02, prefixed: false, repr: "LD (BC),A", num_bytes: 1, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x03, prefixed: false, repr: "INC BC", num_bytes: 1, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x04, prefixed: false, repr: "INC B", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0x05, prefixed: false, repr: "DEC B", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0x06, prefixed: false, repr: "LD B,d8", num_bytes: 2, cycles: Fixed(2), addressing_mode: Imm8 },
    Instruction { opcode: 0x07, prefixed: false, repr: "RLCA", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0x08, prefixed: false, repr: "LD (a16),SP", num_bytes: 3, cycles: Fixed(5), addressing_mode: Addr16 },
    Instruction { opcode: 0x09, prefixed: false, repr: "ADD HL,BC", num_bytes: 1, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x0A, prefixed: false, repr: "LD A,(BC)", num_bytes: 1, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x0B, prefixed: false, repr: "DEC BC", num_bytes: 1, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x0C, prefixed: false, repr: "INC C", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0x0D, prefixed: false, repr: "DEC C", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0x0E, prefixed: false, repr: "LD C,d8", num_bytes: 2, cycles: Fixed(2), addressing_mode: Imm8 },
    Instruction { opcode: 0x0F, prefixed: false, repr: "RRCA", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0x10, prefixed: false, repr: "STOP 0", num_bytes: 2, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0x11, prefixed: false, repr: "LD DE,d16", num_bytes: 3, cycles: Fixed(3), addressing_mode: Imm16 },
    Instruction { opcode: 0x12, prefixed: false, repr: "LD (DE),A", num_bytes: 1, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x13, prefixed: false, repr: "INC DE", num_bytes: 1, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x14, prefixed: false, repr: "INC D", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0x15, prefixed: false, repr: "DEC D", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0x16, prefixed: false, repr: "LD D,d8", num_bytes: 2, cycles: Fixed(2), addressing_mode: Imm8 },
    Instruction { opcode: 0x17, prefixed: false, repr: "RLA", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0x18, prefixed: false, repr: "JR r8", num_bytes: 2, cycles: Fixed(3), addressing_mode: SignedAddrOffset },
    Instruction { opcode: 0x19, prefixed: false, repr: "ADD HL,DE", num_bytes: 1, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x1A, prefixed: false, repr: "LD A,(DE)", num_bytes: 1, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x1B, prefixed: false, repr: "DEC DE", num_bytes: 1, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x1C, prefixed: false, repr: "INC E", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0x1D, prefixed: false, repr: "DEC E", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0x1E, prefixed: false, repr: "LD E,d8", num_bytes: 2, cycles: Fixed(2), addressing_mode: Imm8 },
    Instruction { opcode: 0x1F, prefixed: false, repr: "RRA", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0x20, prefixed: false, repr: "JR NZ,r8", num_bytes: 2, cycles: Jump(3, 2), addressing_mode: SignedAddrOffset },
    Instruction { opcode: 0x21, prefixed: false, repr: "LD HL,d16", num_bytes: 3, cycles: Fixed(3), addressing_mode: Imm16 },
    Instruction { opcode: 0x22, prefixed: false, repr: "LD (HL+),A", num_bytes: 1, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x23, prefixed: false, repr: "INC HL", num_bytes: 1, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x24, prefixed: false, repr: "INC H", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0x25, prefixed: false, repr: "DEC H", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0x26, prefixed: false, repr: "LD H,d8", num_bytes: 2, cycles: Fixed(2), addressing_mode: Imm8 },
    Instruction { opcode: 0x27, prefixed: false, repr: "DAA", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0x28, prefixed: false, repr: "JR Z,r8", num_bytes: 2, cycles: Jump(3, 2), addressing_mode: SignedAddrOffset },
    Instruction { opcode: 0x29, prefixed: false, repr: "ADD HL,HL", num_bytes: 1, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x2A, prefixed: false, repr: "LD A,(HL+)", num_bytes: 1, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x2B, prefixed: false, repr: "DEC HL", num_bytes: 1, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x2C, prefixed: false, repr: "INC L", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0x2D, prefixed: false, repr: "DEC L", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0x2E, prefixed: false, repr: "LD L,d8", num_bytes: 2, cycles: Fixed(2), addressing_mode: Imm8 },
    Instruction { opcode: 0x2F, prefixed: false, repr: "CPL", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0x30, prefixed: false, repr: "JR NC,r8", num_bytes: 2, cycles: Jump(3, 2), addressing_mode: SignedAddrOffset },
    Instruction { opcode: 0x31, prefixed: false, repr: "LD SP,d16", num_bytes: 3, cycles: Fixed(3), addressing_mode: Imm16 },
    Instruction { opcode: 0x32, prefixed: false, repr: "LD (HL-),A", num_bytes: 1, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x33, prefixed: false, repr: "INC SP", num_bytes: 1, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x34, prefixed: false, repr: "INC (HL)", num_bytes: 1, cycles: Fixed(3), addressing_mode: Implied },
    Instruction { opcode: 0x35, prefixed: false, repr: "DEC (HL)", num_bytes: 1, cycles: Fixed(3), addressing_mode: Implied },
    Instruction { opcode: 0x36, prefixed: false, repr: "LD (HL),d8", num_bytes: 2, cycles: Fixed(3), addressing_mode: Imm8 },
    Instruction { opcode: 0x37, prefixed: false, repr: "SCF", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0x38, prefixed: false, repr: "JR C,r8", num_bytes: 2, cycles: Jump(3, 2), addressing_mode: SignedAddrOffset },
    Instruction { opcode: 0x39, prefixed: false, repr: "ADD HL,SP", num_bytes: 1, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x3A, prefixed: false, repr: "LD A,(HL-)", num_bytes: 1, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x3B, prefixed: false, repr: "DEC SP", num_bytes: 1, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x3C, prefixed: false, repr: "INC A", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0x3D, prefixed: false, repr: "DEC A", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0x3E, prefixed: false, repr: "LD A,d8", num_bytes: 2, cycles: Fixed(2), addressing_mode: Imm8 },
    Instruction { opcode: 0x3F, prefixed: false, repr: "CCF", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0x40, prefixed: false, repr: "LD B,B", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0x41, prefixed: false, repr: "LD B,C", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0x42, prefixed: false, repr: "LD B,D", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0x43, prefixed: false, repr: "LD B,E", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0x44, prefixed: false, repr: "LD B,H", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0x45, prefixed: false, repr: "LD B,L", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0x46, prefixed: false, repr: "LD B,(HL)", num_bytes: 1, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x47, prefixed: false, repr: "LD B,A", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0x48, prefixed: false, repr: "LD C,B", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0x49, prefixed: false, repr: "LD C,C", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0x4A, prefixed: false, repr: "LD C,D", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0x4B, prefixed: false, repr: "LD C,E", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0x4C, prefixed: false, repr: "LD C,H", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0x4D, prefixed: false, repr: "LD C,L", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0x4E, prefixed: false, repr: "LD C,(HL)", num_bytes: 1, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x4F, prefixed: false, repr: "LD C,A", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0x50, prefixed: false, repr: "LD D,B", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0x51, prefixed: false, repr: "LD D,C", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0x52, prefixed: false, repr: "LD D,D", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0x53, prefixed: false, repr: "LD D,E", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0x54, prefixed: false, repr: "LD D,H", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0x55, prefixed: false, repr: "LD D,L", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0x56, prefixed: false, repr: "LD D,(HL)", num_bytes: 1, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x57, prefixed: false, repr: "LD D,A", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0x58, prefixed: false, repr: "LD E,B", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0x59, prefixed: false, repr: "LD E,C", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0x5A, prefixed: false, repr: "LD E,D", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0x5B, prefixed: false, repr: "LD E,E", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0x5C, prefixed: false, repr: "LD E,H", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0x5D, prefixed: false, repr: "LD E,L", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0x5E, prefixed: false, repr: "LD E,(HL)", num_bytes: 1, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x5F, prefixed: false, repr: "LD E,A", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0x60, prefixed: false, repr: "LD H,B", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0x61, prefixed: false, repr: "LD H,C", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0x62, prefixed: false, repr: "LD H,D", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0x63, prefixed: false, repr: "LD H,E", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0x64, prefixed: false, repr: "LD H,H", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0x65, prefixed: false, repr: "LD H,L", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0x66, prefixed: false, repr: "LD H,(HL)", num_bytes: 1, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x67, prefixed: false, repr: "LD H,A", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0x68, prefixed: false, repr: "LD L,B", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0x69, prefixed: false, repr: "LD L,C", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0x6A, prefixed: false, repr: "LD L,D", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0x6B, prefixed: false, repr: "LD L,E", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0x6C, prefixed: false, repr: "LD L,H", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0x6D, prefixed: false, repr: "LD L,L", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0x6E, prefixed: false, repr: "LD L,(HL)", num_bytes: 1, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x6F, prefixed: false, repr: "LD L,A", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0x70, prefixed: false, repr: "LD (HL),B", num_bytes: 1, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x71, prefixed: false, repr: "LD (HL),C", num_bytes: 1, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x72, prefixed: false, repr: "LD (HL),D", num_bytes: 1, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x73, prefixed: false, repr: "LD (HL),E", num_bytes: 1, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x74, prefixed: false, repr: "LD (HL),H", num_bytes: 1, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x75, prefixed: false, repr: "LD (HL),L", num_bytes: 1, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x76, prefixed: false, repr: "HALT", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0x77, prefixed: false, repr: "LD (HL),A", num_bytes: 1, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x78, prefixed: false, repr: "LD A,B", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0x79, prefixed: false, repr: "LD A,C", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0x7A, prefixed: false, repr: "LD A,D", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0x7B, prefixed: false, repr: "LD A,E", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0x7C, prefixed: false, repr: "LD A,H", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0x7D, prefixed: false, repr: "LD A,L", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0x7E, prefixed: false, repr: "LD A,(HL)", num_bytes: 1, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x7F, prefixed: false, repr: "LD A,A", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0x80, prefixed: false, repr: "ADD A,B", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0x81, prefixed: false, repr: "ADD A,C", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0x82, prefixed: false, repr: "ADD A,D", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0x83, prefixed: false, repr: "ADD A,E", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0x84, prefixed: false, repr: "ADD A,H", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0x85, prefixed: false, repr: "ADD A,L", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0x86, prefixed: false, repr: "ADD A,(HL)", num_bytes: 1, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x87, prefixed: false, repr: "ADD A,A", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0x88, prefixed: false, repr: "ADC A,B", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0x89, prefixed: false, repr: "ADC A,C", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0x8A, prefixed: false, repr: "ADC A,D", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0x8B, prefixed: false, repr: "ADC A,E", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0x8C, prefixed: false, repr: "ADC A,H", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0x8D, prefixed: false, repr: "ADC A,L", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0x8E, prefixed: false, repr: "ADC A,(HL)", num_bytes: 1, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x8F, prefixed: false, repr: "ADC A,A", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0x90, prefixed: false, repr: "SUB B", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0x91, prefixed: false, repr: "SUB C", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0x92, prefixed: false, repr: "SUB D", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0x93, prefixed: false, repr: "SUB E", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0x94, prefixed: false, repr: "SUB H", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0x95, prefixed: false, repr: "SUB L", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0x96, prefixed: false, repr: "SUB (HL)", num_bytes: 1, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x97, prefixed: false, repr: "SUB A", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0x98, prefixed: false, repr: "SBC A,B", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0x99, prefixed: false, repr: "SBC A,C", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0x9A, prefixed: false, repr: "SBC A,D", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0x9B, prefixed: false, repr: "SBC A,E", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0x9C, prefixed: false, repr: "SBC A,H", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0x9D, prefixed: false, repr: "SBC A,L", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0x9E, prefixed: false, repr: "SBC A,(HL)", num_bytes: 1, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x9F, prefixed: false, repr: "SBC A,A", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0xA0, prefixed: false, repr: "AND B", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0xA1, prefixed: false, repr: "AND C", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0xA2, prefixed: false, repr: "AND D", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0xA3, prefixed: false, repr: "AND E", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0xA4, prefixed: false, repr: "AND H", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0xA5, prefixed: false, repr: "AND L", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0xA6, prefixed: false, repr: "AND (HL)", num_bytes: 1, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0xA7, prefixed: false, repr: "AND A", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0xA8, prefixed: false, repr: "XOR B", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0xA9, prefixed: false, repr: "XOR C", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0xAA, prefixed: false, repr: "XOR D", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0xAB, prefixed: false, repr: "XOR E", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0xAC, prefixed: false, repr: "XOR H", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0xAD, prefixed: false, repr: "XOR L", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0xAE, prefixed: false, repr: "XOR (HL)", num_bytes: 1, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0xAF, prefixed: false, repr: "XOR A", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0xB0, prefixed: false, repr: "OR B", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0xB1, prefixed: false, repr: "OR C", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0xB2, prefixed: false, repr: "OR D", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0xB3, prefixed: false, repr: "OR E", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0xB4, prefixed: false, repr: "OR H", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0xB5, prefixed: false, repr: "OR L", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0xB6, prefixed: false, repr: "OR (HL)", num_bytes: 1, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0xB7, prefixed: false, repr: "OR A", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0xB8, prefixed: false, repr: "CP B", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0xB9, prefixed: false, repr: "CP C", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0xBA, prefixed: false, repr: "CP D", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0xBB, prefixed: false, repr: "CP E", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0xBC, prefixed: false, repr: "CP H", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0xBD, prefixed: false, repr: "CP L", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0xBE, prefixed: false, repr: "CP (HL)", num_bytes: 1, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0xBF, prefixed: false, repr: "CP A", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0xC0, prefixed: false, repr: "RET NZ", num_bytes: 1, cycles: Jump(5, 2), addressing_mode: Implied },
    Instruction { opcode: 0xC1, prefixed: false, repr: "POP BC", num_bytes: 1, cycles: Fixed(3), addressing_mode: Implied },
    Instruction { opcode: 0xC2, prefixed: false, repr: "JP NZ,a16", num_bytes: 3, cycles: Jump(4, 3), addressing_mode: Addr16 },
    Instruction { opcode: 0xC3, prefixed: false, repr: "JP a16", num_bytes: 3, cycles: Fixed(4), addressing_mode: Addr16 },
    Instruction { opcode: 0xC4, prefixed: false, repr: "CALL NZ,a16", num_bytes: 3, cycles: Jump(6, 3), addressing_mode: Addr16 },
    Instruction { opcode: 0xC5, prefixed: false, repr: "PUSH BC", num_bytes: 1, cycles: Fixed(4), addressing_mode: Implied },
    Instruction { opcode: 0xC6, prefixed: false, repr: "ADD A,d8", num_bytes: 2, cycles: Fixed(2), addressing_mode: Imm8 },
    Instruction { opcode: 0xC7, prefixed: false, repr: "RST 00H", num_bytes: 1, cycles: Fixed(4), addressing_mode: Implied },
    Instruction { opcode: 0xC8, prefixed: false, repr: "RET Z", num_bytes: 1, cycles: Jump(5, 2), addressing_mode: Implied },
    Instruction { opcode: 0xC9, prefixed: false, repr: "RET", num_bytes: 1, cycles: Fixed(4), addressing_mode: Implied },
    Instruction { opcode: 0xCA, prefixed: false, repr: "JP Z,a16", num_bytes: 3, cycles: Jump(4, 3), addressing_mode: Addr16 },
    Instruction { opcode: 0xCB, prefixed: false, repr: "PREFIX CB", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0xCC, prefixed: false, repr: "CALL Z,a16", num_bytes: 3, cycles: Jump(6, 3), addressing_mode: Addr16 },
    Instruction { opcode: 0xCD, prefixed: false, repr: "CALL a16", num_bytes: 3, cycles: Fixed(6), addressing_mode: Addr16 },
    Instruction { opcode: 0xCE, prefixed: false, repr: "ADC A,d8", num_bytes: 2, cycles: Fixed(2), addressing_mode: Imm8 },
    Instruction { opcode: 0xCF, prefixed: false, repr: "RST 08H", num_bytes: 1, cycles: Fixed(4), addressing_mode: Implied },
    Instruction { opcode: 0xD0, prefixed: false, repr: "RET NC", num_bytes: 1, cycles: Jump(5, 2), addressing_mode: Implied },
    Instruction { opcode: 0xD1, prefixed: false, repr: "POP DE", num_bytes: 1, cycles: Fixed(3), addressing_mode: Implied },
    Instruction { opcode: 0xD2, prefixed: false, repr: "JP NC,a16", num_bytes: 3, cycles: Jump(4, 3), addressing_mode: Addr16 },
    Instruction { opcode: 0xD3, prefixed: false, repr: "UNIMPLEMENTED", num_bytes: 0, cycles: Fixed(0), addressing_mode: Addr16 },
    Instruction { opcode: 0xD4, prefixed: false, repr: "CALL NC,a16", num_bytes: 3, cycles: Jump(6, 3), addressing_mode: Addr16 },
    Instruction { opcode: 0xD5, prefixed: false, repr: "PUSH DE", num_bytes: 1, cycles: Fixed(4), addressing_mode: Implied },
    Instruction { opcode: 0xD6, prefixed: false, repr: "SUB d8", num_bytes: 2, cycles: Fixed(2), addressing_mode: Imm8 },
    Instruction { opcode: 0xD7, prefixed: false, repr: "RST 10H", num_bytes: 1, cycles: Fixed(4), addressing_mode: Implied },
    Instruction { opcode: 0xD8, prefixed: false, repr: "RET C", num_bytes: 1, cycles: Jump(5, 2), addressing_mode: Implied },
    Instruction { opcode: 0xD9, prefixed: false, repr: "RETI", num_bytes: 1, cycles: Fixed(4), addressing_mode: Implied },
    Instruction { opcode: 0xDA, prefixed: false, repr: "JP C,a16", num_bytes: 3, cycles: Jump(4, 3), addressing_mode: Addr16 },
    Instruction { opcode: 0xDB, prefixed: false, repr: "UNIMPLEMENTED", num_bytes: 0, cycles: Fixed(0), addressing_mode: Addr16 },
    Instruction { opcode: 0xDC, prefixed: false, repr: "CALL C,a16", num_bytes: 3, cycles: Jump(6, 3), addressing_mode: Addr16 },
    Instruction { opcode: 0xDD, prefixed: false, repr: "UNIMPLEMENTED", num_bytes: 0, cycles: Fixed(0), addressing_mode: Addr16 },
    Instruction { opcode: 0xDE, prefixed: false, repr: "SBC A,d8", num_bytes: 2, cycles: Fixed(2), addressing_mode: Imm8 },
    Instruction { opcode: 0xDF, prefixed: false, repr: "RST 18H", num_bytes: 1, cycles: Fixed(4), addressing_mode: Implied },
    Instruction { opcode: 0xE0, prefixed: false, repr: "LDH (a8),A", num_bytes: 2, cycles: Fixed(3), addressing_mode: ZeroPageOffset },
    Instruction { opcode: 0xE1, prefixed: false, repr: "POP HL", num_bytes: 1, cycles: Fixed(3), addressing_mode: Implied },
    Instruction { opcode: 0xE2, prefixed: false, repr: "LD (C),A", num_bytes: 1, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0xE3, prefixed: false, repr: "UNIMPLEMENTED", num_bytes: 0, cycles: Fixed(0), addressing_mode: ZeroPageOffset },
    Instruction { opcode: 0xE4, prefixed: false, repr: "UNIMPLEMENTED", num_bytes: 0, cycles: Fixed(0), addressing_mode: ZeroPageOffset },
    Instruction { opcode: 0xE5, prefixed: false, repr: "PUSH HL", num_bytes: 1, cycles: Fixed(4), addressing_mode: Implied },
    Instruction { opcode: 0xE6, prefixed: false, repr: "AND d8", num_bytes: 2, cycles: Fixed(2), addressing_mode: Imm8 },
    Instruction { opcode: 0xE7, prefixed: false, repr: "RST 20H", num_bytes: 1, cycles: Fixed(4), addressing_mode: Implied },
    Instruction { opcode: 0xE8, prefixed: false, repr: "ADD SP,r8", num_bytes: 2, cycles: Fixed(4), addressing_mode: SignedAddrOffset },
    Instruction { opcode: 0xE9, prefixed: false, repr: "JP (HL)", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0xEA, prefixed: false, repr: "LD (a16),A", num_bytes: 3, cycles: Fixed(4), addressing_mode: Addr16 },
    Instruction { opcode: 0xEB, prefixed: false, repr: "UNIMPLEMENTED", num_bytes: 0, cycles: Fixed(0), addressing_mode: Addr16 },
    Instruction { opcode: 0xEC, prefixed: false, repr: "UNIMPLEMENTED", num_bytes: 0, cycles: Fixed(0), addressing_mode: Addr16 },
    Instruction { opcode: 0xED, prefixed: false, repr: "UNIMPLEMENTED", num_bytes: 0, cycles: Fixed(0), addressing_mode: Addr16 },
    Instruction { opcode: 0xEE, prefixed: false, repr: "XOR d8", num_bytes: 2, cycles: Fixed(2), addressing_mode: Imm8 },
    Instruction { opcode: 0xEF, prefixed: false, repr: "RST 28H", num_bytes: 1, cycles: Fixed(4), addressing_mode: Implied },
    Instruction { opcode: 0xF0, prefixed: false, repr: "LDH A,(a8)", num_bytes: 2, cycles: Fixed(3), addressing_mode: ZeroPageOffset },
    Instruction { opcode: 0xF1, prefixed: false, repr: "POP AF", num_bytes: 1, cycles: Fixed(3), addressing_mode: Implied },
    Instruction { opcode: 0xF2, prefixed: false, repr: "LD A,(C)", num_bytes: 1, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0xF3, prefixed: false, repr: "DI", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0xF4, prefixed: false, repr: "UNIMPLEMENTED", num_bytes: 0, cycles: Fixed(0), addressing_mode: Implied },
    Instruction { opcode: 0xF5, prefixed: false, repr: "PUSH AF", num_bytes: 1, cycles: Fixed(4), addressing_mode: Implied },
    Instruction { opcode: 0xF6, prefixed: false, repr: "OR d8", num_bytes: 2, cycles: Fixed(2), addressing_mode: Imm8 },
    Instruction { opcode: 0xF7, prefixed: false, repr: "RST 30H", num_bytes: 1, cycles: Fixed(4), addressing_mode: Implied },
    Instruction { opcode: 0xF8, prefixed: false, repr: "LD HL,SP+r8", num_bytes: 2, cycles: Fixed(3), addressing_mode: SignedAddrOffset },
    Instruction { opcode: 0xF9, prefixed: false, repr: "LD SP,HL", num_bytes: 1, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0xFA, prefixed: false, repr: "LD A,(a16)", num_bytes: 3, cycles: Fixed(4), addressing_mode: Addr16 },
    Instruction { opcode: 0xFB, prefixed: false, repr: "EI", num_bytes: 1, cycles: Fixed(1), addressing_mode: Implied },
    Instruction { opcode: 0xFC, prefixed: false, repr: "UNIMPLEMENTED", num_bytes: 0, cycles: Fixed(0), addressing_mode: Implied },
    Instruction { opcode: 0xFD, prefixed: false, repr: "UNIMPLEMENTED", num_bytes: 0, cycles: Fixed(0), addressing_mode: Implied },
    Instruction { opcode: 0xFE, prefixed: false, repr: "CP d8", num_bytes: 2, cycles: Fixed(2), addressing_mode: Imm8 },
    Instruction { opcode: 0xFF, prefixed: false, repr: "RST 38H", num_bytes: 1, cycles: Fixed(4), addressing_mode: Implied },
];

pub static PREFIXED_INSTRUCTIONS: [Instruction; 256] = [
    Instruction { opcode: 0x00, prefixed: true, repr: "RLC B", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x01, prefixed: true, repr: "RLC C", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x02, prefixed: true, repr: "RLC D", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x03, prefixed: true, repr: "RLC E", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x04, prefixed: true, repr: "RLC H", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x05, prefixed: true, repr: "RLC L", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x06, prefixed: true, repr: "RLC (HL)", num_bytes: 2, cycles: Fixed(4), addressing_mode: Implied },
    Instruction { opcode: 0x07, prefixed: true, repr: "RLC A", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x08, prefixed: true, repr: "RRC B", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x09, prefixed: true, repr: "RRC C", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x0A, prefixed: true, repr: "RRC D", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x0B, prefixed: true, repr: "RRC E", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x0C, prefixed: true, repr: "RRC H", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x0D, prefixed: true, repr: "RRC L", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x0E, prefixed: true, repr: "RRC (HL)", num_bytes: 2, cycles: Fixed(4), addressing_mode: Implied },
    Instruction { opcode: 0x0F, prefixed: true, repr: "RRC A", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x10, prefixed: true, repr: "RL B", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x11, prefixed: true, repr: "RL C", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x12, prefixed: true, repr: "RL D", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x13, prefixed: true, repr: "RL E", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x14, prefixed: true, repr: "RL H", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x15, prefixed: true, repr: "RL L", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x16, prefixed: true, repr: "RL (HL)", num_bytes: 2, cycles: Fixed(4), addressing_mode: Implied },
    Instruction { opcode: 0x17, prefixed: true, repr: "RL A", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x18, prefixed: true, repr: "RR B", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x19, prefixed: true, repr: "RR C", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x1A, prefixed: true, repr: "RR D", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x1B, prefixed: true, repr: "RR E", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x1C, prefixed: true, repr: "RR H", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x1D, prefixed: true, repr: "RR L", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x1E, prefixed: true, repr: "RR (HL)", num_bytes: 2, cycles: Fixed(4), addressing_mode: Implied },
    Instruction { opcode: 0x1F, prefixed: true, repr: "RR A", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x20, prefixed: true, repr: "SLA B", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x21, prefixed: true, repr: "SLA C", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x22, prefixed: true, repr: "SLA D", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x23, prefixed: true, repr: "SLA E", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x24, prefixed: true, repr: "SLA H", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x25, prefixed: true, repr: "SLA L", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x26, prefixed: true, repr: "SLA (HL)", num_bytes: 2, cycles: Fixed(4), addressing_mode: Implied },
    Instruction { opcode: 0x27, prefixed: true, repr: "SLA A", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x28, prefixed: true, repr: "SRA B", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x29, prefixed: true, repr: "SRA C", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x2A, prefixed: true, repr: "SRA D", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x2B, prefixed: true, repr: "SRA E", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x2C, prefixed: true, repr: "SRA H", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x2D, prefixed: true, repr: "SRA L", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x2E, prefixed: true, repr: "SRA (HL)", num_bytes: 2, cycles: Fixed(4), addressing_mode: Implied },
    Instruction { opcode: 0x2F, prefixed: true, repr: "SRA A", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x30, prefixed: true, repr: "SWAP B", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x31, prefixed: true, repr: "SWAP C", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x32, prefixed: true, repr: "SWAP D", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x33, prefixed: true, repr: "SWAP E", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x34, prefixed: true, repr: "SWAP H", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x35, prefixed: true, repr: "SWAP L", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x36, prefixed: true, repr: "SWAP (HL)", num_bytes: 2, cycles: Fixed(4), addressing_mode: Implied },
    Instruction { opcode: 0x37, prefixed: true, repr: "SWAP A", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x38, prefixed: true, repr: "SRL B", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x39, prefixed: true, repr: "SRL C", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x3A, prefixed: true, repr: "SRL D", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x3B, prefixed: true, repr: "SRL E", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x3C, prefixed: true, repr: "SRL H", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x3D, prefixed: true, repr: "SRL L", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x3E, prefixed: true, repr: "SRL (HL)", num_bytes: 2, cycles: Fixed(4), addressing_mode: Implied },
    Instruction { opcode: 0x3F, prefixed: true, repr: "SRL A", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x40, prefixed: true, repr: "BIT 0,B", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x41, prefixed: true, repr: "BIT 0,C", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x42, prefixed: true, repr: "BIT 0,D", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x43, prefixed: true, repr: "BIT 0,E", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x44, prefixed: true, repr: "BIT 0,H", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x45, prefixed: true, repr: "BIT 0,L", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x46, prefixed: true, repr: "BIT 0,(HL)", num_bytes: 2, cycles: Fixed(3), addressing_mode: Implied },
    Instruction { opcode: 0x47, prefixed: true, repr: "BIT 0,A", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x48, prefixed: true, repr: "BIT 1,B", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x49, prefixed: true, repr: "BIT 1,C", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x4A, prefixed: true, repr: "BIT 1,D", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x4B, prefixed: true, repr: "BIT 1,E", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x4C, prefixed: true, repr: "BIT 1,H", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x4D, prefixed: true, repr: "BIT 1,L", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x4E, prefixed: true, repr: "BIT 1,(HL)", num_bytes: 2, cycles: Fixed(3), addressing_mode: Implied },
    Instruction { opcode: 0x4F, prefixed: true, repr: "BIT 1,A", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x50, prefixed: true, repr: "BIT 2,B", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x51, prefixed: true, repr: "BIT 2,C", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x52, prefixed: true, repr: "BIT 2,D", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x53, prefixed: true, repr: "BIT 2,E", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x54, prefixed: true, repr: "BIT 2,H", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x55, prefixed: true, repr: "BIT 2,L", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x56, prefixed: true, repr: "BIT 2,(HL)", num_bytes: 2, cycles: Fixed(3), addressing_mode: Implied },
    Instruction { opcode: 0x57, prefixed: true, repr: "BIT 2,A", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x58, prefixed: true, repr: "BIT 3,B", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x59, prefixed: true, repr: "BIT 3,C", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x5A, prefixed: true, repr: "BIT 3,D", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x5B, prefixed: true, repr: "BIT 3,E", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x5C, prefixed: true, repr: "BIT 3,H", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x5D, prefixed: true, repr: "BIT 3,L", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x5E, prefixed: true, repr: "BIT 3,(HL)", num_bytes: 2, cycles: Fixed(3), addressing_mode: Implied },
    Instruction { opcode: 0x5F, prefixed: true, repr: "BIT 3,A", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x60, prefixed: true, repr: "BIT 4,B", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x61, prefixed: true, repr: "BIT 4,C", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x62, prefixed: true, repr: "BIT 4,D", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x63, prefixed: true, repr: "BIT 4,E", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x64, prefixed: true, repr: "BIT 4,H", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x65, prefixed: true, repr: "BIT 4,L", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x66, prefixed: true, repr: "BIT 4,(HL)", num_bytes: 2, cycles: Fixed(3), addressing_mode: Implied },
    Instruction { opcode: 0x67, prefixed: true, repr: "BIT 4,A", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x68, prefixed: true, repr: "BIT 5,B", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x69, prefixed: true, repr: "BIT 5,C", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x6A, prefixed: true, repr: "BIT 5,D", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x6B, prefixed: true, repr: "BIT 5,E", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x6C, prefixed: true, repr: "BIT 5,H", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x6D, prefixed: true, repr: "BIT 5,L", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x6E, prefixed: true, repr: "BIT 5,(HL)", num_bytes: 2, cycles: Fixed(3), addressing_mode: Implied },
    Instruction { opcode: 0x6F, prefixed: true, repr: "BIT 5,A", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x70, prefixed: true, repr: "BIT 6,B", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x71, prefixed: true, repr: "BIT 6,C", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x72, prefixed: true, repr: "BIT 6,D", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x73, prefixed: true, repr: "BIT 6,E", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x74, prefixed: true, repr: "BIT 6,H", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x75, prefixed: true, repr: "BIT 6,L", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x76, prefixed: true, repr: "BIT 6,(HL)", num_bytes: 2, cycles: Fixed(3), addressing_mode: Implied },
    Instruction { opcode: 0x77, prefixed: true, repr: "BIT 6,A", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x78, prefixed: true, repr: "BIT 7,B", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x79, prefixed: true, repr: "BIT 7,C", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x7A, prefixed: true, repr: "BIT 7,D", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x7B, prefixed: true, repr: "BIT 7,E", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x7C, prefixed: true, repr: "BIT 7,H", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x7D, prefixed: true, repr: "BIT 7,L", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x7E, prefixed: true, repr: "BIT 7,(HL)", num_bytes: 2, cycles: Fixed(3), addressing_mode: Implied },
    Instruction { opcode: 0x7F, prefixed: true, repr: "BIT 7,A", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x80, prefixed: true, repr: "RES 0,B", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x81, prefixed: true, repr: "RES 0,C", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x82, prefixed: true, repr: "RES 0,D", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x83, prefixed: true, repr: "RES 0,E", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x84, prefixed: true, repr: "RES 0,H", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x85, prefixed: true, repr: "RES 0,L", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x86, prefixed: true, repr: "RES 0,(HL)", num_bytes: 2, cycles: Fixed(4), addressing_mode: Implied },
    Instruction { opcode: 0x87, prefixed: true, repr: "RES 0,A", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x88, prefixed: true, repr: "RES 1,B", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x89, prefixed: true, repr: "RES 1,C", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x8A, prefixed: true, repr: "RES 1,D", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x8B, prefixed: true, repr: "RES 1,E", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x8C, prefixed: true, repr: "RES 1,H", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x8D, prefixed: true, repr: "RES 1,L", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x8E, prefixed: true, repr: "RES 1,(HL)", num_bytes: 2, cycles: Fixed(4), addressing_mode: Implied },
    Instruction { opcode: 0x8F, prefixed: true, repr: "RES 1,A", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x90, prefixed: true, repr: "RES 2,B", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x91, prefixed: true, repr: "RES 2,C", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x92, prefixed: true, repr: "RES 2,D", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x93, prefixed: true, repr: "RES 2,E", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x94, prefixed: true, repr: "RES 2,H", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x95, prefixed: true, repr: "RES 2,L", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x96, prefixed: true, repr: "RES 2,(HL)", num_bytes: 2, cycles: Fixed(4), addressing_mode: Implied },
    Instruction { opcode: 0x97, prefixed: true, repr: "RES 2,A", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x98, prefixed: true, repr: "RES 3,B", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x99, prefixed: true, repr: "RES 3,C", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x9A, prefixed: true, repr: "RES 3,D", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x9B, prefixed: true, repr: "RES 3,E", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x9C, prefixed: true, repr: "RES 3,H", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x9D, prefixed: true, repr: "RES 3,L", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0x9E, prefixed: true, repr: "RES 3,(HL)", num_bytes: 2, cycles: Fixed(4), addressing_mode: Implied },
    Instruction { opcode: 0x9F, prefixed: true, repr: "RES 3,A", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0xA0, prefixed: true, repr: "RES 4,B", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0xA1, prefixed: true, repr: "RES 4,C", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0xA2, prefixed: true, repr: "RES 4,D", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0xA3, prefixed: true, repr: "RES 4,E", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0xA4, prefixed: true, repr: "RES 4,H", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0xA5, prefixed: true, repr: "RES 4,L", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0xA6, prefixed: true, repr: "RES 4,(HL)", num_bytes: 2, cycles: Fixed(4), addressing_mode: Implied },
    Instruction { opcode: 0xA7, prefixed: true, repr: "RES 4,A", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0xA8, prefixed: true, repr: "RES 5,B", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0xA9, prefixed: true, repr: "RES 5,C", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0xAA, prefixed: true, repr: "RES 5,D", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0xAB, prefixed: true, repr: "RES 5,E", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0xAC, prefixed: true, repr: "RES 5,H", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0xAD, prefixed: true, repr: "RES 5,L", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0xAE, prefixed: true, repr: "RES 5,(HL)", num_bytes: 2, cycles: Fixed(4), addressing_mode: Implied },
    Instruction { opcode: 0xAF, prefixed: true, repr: "RES 5,A", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0xB0, prefixed: true, repr: "RES 6,B", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0xB1, prefixed: true, repr: "RES 6,C", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0xB2, prefixed: true, repr: "RES 6,D", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0xB3, prefixed: true, repr: "RES 6,E", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0xB4, prefixed: true, repr: "RES 6,H", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0xB5, prefixed: true, repr: "RES 6,L", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0xB6, prefixed: true, repr: "RES 6,(HL)", num_bytes: 2, cycles: Fixed(4), addressing_mode: Implied },
    Instruction { opcode: 0xB7, prefixed: true, repr: "RES 6,A", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0xB8, prefixed: true, repr: "RES 7,B", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0xB9, prefixed: true, repr: "RES 7,C", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0xBA, prefixed: true, repr: "RES 7,D", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0xBB, prefixed: true, repr: "RES 7,E", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0xBC, prefixed: true, repr: "RES 7,H", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0xBD, prefixed: true, repr: "RES 7,L", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0xBE, prefixed: true, repr: "RES 7,(HL)", num_bytes: 2, cycles: Fixed(4), addressing_mode: Implied },
    Instruction { opcode: 0xBF, prefixed: true, repr: "RES 7,A", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0xC0, prefixed: true, repr: "SET 0,B", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0xC1, prefixed: true, repr: "SET 0,C", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0xC2, prefixed: true, repr: "SET 0,D", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0xC3, prefixed: true, repr: "SET 0,E", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0xC4, prefixed: true, repr: "SET 0,H", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0xC5, prefixed: true, repr: "SET 0,L", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0xC6, prefixed: true, repr: "SET 0,(HL)", num_bytes: 2, cycles: Fixed(4), addressing_mode: Implied },
    Instruction { opcode: 0xC7, prefixed: true, repr: "SET 0,A", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0xC8, prefixed: true, repr: "SET 1,B", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0xC9, prefixed: true, repr: "SET 1,C", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0xCA, prefixed: true, repr: "SET 1,D", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0xCB, prefixed: true, repr: "SET 1,E", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0xCC, prefixed: true, repr: "SET 1,H", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0xCD, prefixed: true, repr: "SET 1,L", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0xCE, prefixed: true, repr: "SET 1,(HL)", num_bytes: 2, cycles: Fixed(4), addressing_mode: Implied },
    Instruction { opcode: 0xCF, prefixed: true, repr: "SET 1,A", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0xD0, prefixed: true, repr: "SET 2,B", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0xD1, prefixed: true, repr: "SET 2,C", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0xD2, prefixed: true, repr: "SET 2,D", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0xD3, prefixed: true, repr: "SET 2,E", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0xD4, prefixed: true, repr: "SET 2,H", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0xD5, prefixed: true, repr: "SET 2,L", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0xD6, prefixed: true, repr: "SET 2,(HL)", num_bytes: 2, cycles: Fixed(4), addressing_mode: Implied },
    Instruction { opcode: 0xD7, prefixed: true, repr: "SET 2,A", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0xD8, prefixed: true, repr: "SET 3,B", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0xD9, prefixed: true, repr: "SET 3,C", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0xDA, prefixed: true, repr: "SET 3,D", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0xDB, prefixed: true, repr: "SET 3,E", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0xDC, prefixed: true, repr: "SET 3,H", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0xDD, prefixed: true, repr: "SET 3,L", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0xDE, prefixed: true, repr: "SET 3,(HL)", num_bytes: 2, cycles: Fixed(4), addressing_mode: Implied },
    Instruction { opcode: 0xDF, prefixed: true, repr: "SET 3,A", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0xE0, prefixed: true, repr: "SET 4,B", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0xE1, prefixed: true, repr: "SET 4,C", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0xE2, prefixed: true, repr: "SET 4,D", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0xE3, prefixed: true, repr: "SET 4,E", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0xE4, prefixed: true, repr: "SET 4,H", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0xE5, prefixed: true, repr: "SET 4,L", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0xE6, prefixed: true, repr: "SET 4,(HL)", num_bytes: 2, cycles: Fixed(4), addressing_mode: Implied },
    Instruction { opcode: 0xE7, prefixed: true, repr: "SET 4,A", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0xE8, prefixed: true, repr: "SET 5,B", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0xE9, prefixed: true, repr: "SET 5,C", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0xEA, prefixed: true, repr: "SET 5,D", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0xEB, prefixed: true, repr: "SET 5,E", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0xEC, prefixed: true, repr: "SET 5,H", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0xED, prefixed: true, repr: "SET 5,L", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0xEE, prefixed: true, repr: "SET 5,(HL)", num_bytes: 2, cycles: Fixed(4), addressing_mode: Implied },
    Instruction { opcode: 0xEF, prefixed: true, repr: "SET 5,A", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0xF0, prefixed: true, repr: "SET 6,B", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0xF1, prefixed: true, repr: "SET 6,C", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0xF2, prefixed: true, repr: "SET 6,D", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0xF3, prefixed: true, repr: "SET 6,E", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0xF4, prefixed: true, repr: "SET 6,H", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0xF5, prefixed: true, repr: "SET 6,L", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0xF6, prefixed: true, repr: "SET 6,(HL)", num_bytes: 2, cycles: Fixed(4), addressing_mode: Implied },
    Instruction { opcode: 0xF7, prefixed: true, repr: "SET 6,A", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0xF8, prefixed: true, repr: "SET 7,B", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0xF9, prefixed: true, repr: "SET 7,C", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0xFA, prefixed: true, repr: "SET 7,D", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0xFB, prefixed: true, repr: "SET 7,E", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0xFC, prefixed: true, repr: "SET 7,H", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0xFD, prefixed: true, repr: "SET 7,L", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
    Instruction { opcode: 0xFE, prefixed: true, repr: "SET 7,(HL)", num_bytes: 2, cycles: Fixed(4), addressing_mode: Implied },
    Instruction { opcode: 0xFF, prefixed: true, repr: "SET 7,A", num_bytes: 2, cycles: Fixed(2), addressing_mode: Implied },
];
